### ISSUE TITLE
Not working with (function($) {...})( jQuery );

### ISSUE THREAD

**Issue by patricebriand** [olback/es6-css-minify#1]
Hi, 

While it seems working fine with a "flat" javascript, encapsulating it with jQuery incompatible mention like (function($) {YOUR CODE})( jQuery ); make it screwed, the inside code is almost completely missed.

This is useful when integrating your javascript in a third party environment using Drupal.

Do you have any suggestion for that use case ?

Kind regards.

Patrice.

**Comment by olback** [comment]
@patricebriand If you could provide a code-example for testing. I'd love to investigate.

**Comment by patricebriand** [comment]
Here is a basic example where I can reproduce the issue.
Considering a basic class that will create a div with some custom text.
The class is not called from within the source (that might be the pb) as it is call by the website where this code will be embed (drupal in my case, forcing me to use the jQuery encapsulation).

(function($) {
    class showDivWithText {
        constructor(param) {
            this.text = param;
            this.init();
        }

        init() {
            $("<div />").text(this.text).appendTo('body');
        }
    }
})( jQuery );

**Comment by olback** [comment]
@patricebriand 
Output looks like this now: 
Before:
```javascript
jQuery;
```
After:
```javascript
!function(t){class i{constructor(t){this.text=t,this.init()}init(){t('<div />').text(this.text).appendTo('body')}}}(jQuery);

Looks better?

**Comment by patricebriand** [comment]
Indeed, much better :) 
Any idea when this could be included in a release ?
Your plugin definitely makes sense as the basic minifier does not support classes.
Thank you.

**Comment by olback** [comment]
It will probably be up in an hour or so :)
Thanks for reporting!

**Comment by patricebriand** [comment]
You rocks. Thank you !

**Comment by olback** [comment]
Should be live now!
@patricebriand

**Comment by patricebriand** [comment]
I confirm, it is fixed now.
Thank you again.
Have a nice weekend.
