### ISSUE TITLE
Dont work with Live Sass Compiler ext

### ISSUE THREAD

**Issue by marcellopagano** [olback/es6-css-minify#102]
When I try to your extension using it from visual studio code with "Live Sass Compiler ext" enabling "watch sass" I only get the updated css while the min.css is not updated correctly, while if I go to the css file and save then the min.css file is updated, I confirm that I have changed "es6-css-minify.minifyOnSave": "yes"

Desktop information:
 - OS: win10 64bit 1909
 - Visual studio code 1.43
 - Live sass compiler 3.0.0
 - JS & CSS Minifier (Minify) 3.3.2

**Comment by olback** [comment]
JS & CSS Minifier does not react to file changes, only save events. So when Live Sass compiler saves a new version/file, JS & CSS Minifier does not get notified. If you want minified output from Live Sass Compiler you could add the following to your `.vscode/settings.json`:
```json
{
    "liveSassCompile.settings.formats": [
        {
            "format": "compressed",
            "extensionName": ".min.css",
            "savePath": null
        }
    ]
}
```

**Comment by marcellopagano** [comment]
Thanks for the tip, I would like to know if there is a substantial difference between the (CSS) compression done by "Live sass compiler" and "JS & CSS Minifier (Minify)", I apologize again if the question is a little off topic.

**Comment by olback** [comment]
That's a good question. I think Live Sass Compiler has similar settings to clean-css which is used by 'JS & CSS Minifier'.

**Comment by marcellopagano** [comment]
Thanks again for your time, good job.
