### ISSUE TITLE
How to keep important comments?

### ISSUE THREAD

**Issue by fkoeppling** [olback/es6-css-minify#105]
When minifying .js files, I'd like to **keep important comments** like licence information and other stuff. I've searched all documentation for your extension and the documentation of the dependencies but I'm unable to find an answer for this. I'd be very happy for more insight on this matter!

I'm using _JS & CSS Minifier_ for _VScode_ on Windows.
Thanks in advance!

**Comment by fkoeppling** [comment]
### EDIT*
Found out by testing that this markup keeps comments:
Add a **exclamation mark** to the start tag of a comment-block. Works with _multi-line_ and _documentation_ comment blocks, but **not** with _single-line_ comments.

#### Multi-line comments:
> /&ast;**!**
> comment content
> &ast;/


#### Multi-line documentation comments:
> /&ast;&ast;**!**
> &ast; comment content
> &ast;/

Apologies for opening this issue without proper testing beforehand. It wasn't this obvious to me. May this entry on Q&A help answering those wondering the same in the future.

**Comment by olback** [comment]
Documentation for this extension is not particularly good. I don't blame you for opening an issue. Glad you figured it out though.
