### ISSUE TITLE
Source map

### ISSUE THREAD

**Issue by AndrewHani** [olback/es6-css-minify#11]
Uglify can generate a source map file, but it's not clear how to configure 'es6-css-minify' on visual studio code to generate it.

**Comment by olback** [comment]
Will take a look at it.

**Comment by olback** [comment]
With version 0.1.0 you can enable source maps for both Javascript and CSS in settings.

**Comment by AndrewHani** [comment]
Thanks for your response, but how do I configure it, what are the syntax?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by AndrewHani** [comment]
Dears,
I read your readme file and I have the info now.
Thanks

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
