### ISSUE TITLE
Can't disable for dedicated workspace

### ISSUE THREAD

**Issue by Offerel** [olback/es6-css-minify#113]
**Describe the bug**
I have enabled the extension globally and set minify enabled to yes globally. However, i have one workspace, where i didn't want to minifiy *.js and *.css files. Thats why, i have set minify on save to no for this workspace. However, when i save a *.js file in this workspace, a minified version appears immediately. 

**To Reproduce**
1. Go to 'Extensions'
2. Enable the extension globally
3. Go to settings / tab user
4. Set minify on save = yes
5. Go to settings / tab workspace
6. Set minify on safe = no
7. Open some *.js file from this workspace
8. Edit file
9. save it
10. minified version of *.js file is created

**Expected behavior**
If set minify on save to "no" on workspace, it should be disabled for this special workspace

**Desktop (please complete the following information):**
 - OS: WIndows 10

**Comment by olback** [comment]
In your workspace, please run `Minify: Export Configuration` and reply with the content.

**Comment by Offerel** [comment]
Hi there. Sure, here it is:

```
{
    "minifyOnSave": "no",
    "hideButton": "auto",
    "showLogOnWarning": true,
    "showLogOnError": true,
    "onSaveDelay": 0,
    "uglifyConfigFile": ".uglifyrc",
    "genJSmap": false,
    "jsMapSource": "",
    "jsMinPath": "",
    "jsPostfix": "min",
    "js": {
        "mangle": false,
        "compress": {
            "unused": false
        },
        "output": {
            "quote_style": 0
        },
        "warnings": true,
        "sourceMap": false
    },
    "cleancssConfigFile": ".cleancssrc",
    "genCSSmap": false,
    "cssMapSource": "",
    "cssMinPath": "",
    "cssPostfix": "min",
    "css": {
        "rebase": false,
        "sourceMap": false
    },
    "enableAutoprefixer": false,
    "enableAutoprefixerSelection": false,
    "autoprefixer": {},
    "autoprefixerConfigFile": ".autoprefixerrc"
}
```

**Comment by Offerel** [comment]
It seems, that i could workaround the issue now. If i set in user settings this switch to "no", i can enable it for specific workspaces. And indeed, in that workspaces the minify works now automatically as expected. If i disable it in other specific workspaces and set it there also to "no", no minified versions will be created.

But when i have set in user settings minify to yes, the "no" setting for dedicated workspaces will be ignored.

I assumed, that most of my work will use a minified version, so i set this setting globally to "yes", to have it enabled in every new workspace by default and only disable it at least 2 workspaces, where minified versions will treated as warning (at least this was the case, some months ago, don't know if this is changed on Mozilla WebExtension backend). 

Anyway, i can live with this workaround. But maybe my finding will help you to understand my setup.
