### ISSUE TITLE
Help needed with .unifyrc

### ISSUE THREAD

**Issue by martonx** [olback/es6-css-minify#12]
Its ok then in theory we can set minification options in .unifyrc, but I'm not able to find any documentation for it, hogy to minify the code in ES6/7 compatible format. As I see by default the minified code is ES5, but it should be at least ES6.

**Comment by olback** [comment]
I don't really know what you're asking? Your code shouldn't get converted. Just minified. `const` or `let` doesn't get converted to `var` and so forth. Also, the file I think you're referring to should be named `.uglifyrc` and not `.unifyrc` unless you changed it in settings.

**Comment by martonx** [comment]
Sorry, yes uglifyrc.

Here you are one example:

```
const CACHE = 'v1';

self.addEventListener('install', event => {
    self.skipWaiting();

    event.waitUntil(
        caches.open(CACHE).then(cache => {
            return cache.addAll([
                '/',
                '/manifest.json',
                '/fonts/fontello/css/fontello.css'
            ]);
        })
    );
});

self.addEventListener('fetch', event => {
    //Using cacheFirst methodology
    event.respondWith(fromCache(event.request));
    event.waitUntil(update(event.request));
});

function fromCache(request) {
    return caches.open(CACHE).then(cache => {
        return cache.match(request).then(matching => {
            return matching;
        });
    });
}

function update(request) {
    return caches.open(CACHE).then(cache => {
        return fetch(request).then(response => {
            return cache.put(request, response);
        });
    });
}
```

And this is minified to this:
`const CACHE="v1";function fromCache(e){return caches.open(CACHE).then(t=>t.match(e).then(e=>e))}function update(e){return caches.open(CACHE).then(t=>fetch(e).then(n=>t.put(e,n)))}self.addEventListener("install",e=>{self.skipWaiting(),e.waitUntil(caches.open(CACHE).then(e=>e.addAll(["/","/manifest.json","/fonts/fontello/css/fontello.css"])))}),self.addEventListener("fetch",e=>{e.respondWith(fromCache(e.request)),e.waitUntil(update(e.request))});`

Ah and yes, you're right, it was my mistake I checked minified code contains functions instead of arrow syntax, but this is ok. By the way, how can I use shorten function names in minified code. For example 'fromCache' should be only 'a'?

**Comment by olback** [comment]
_ By the way, how can I use shorten function names in minified code. For example 'fromCache' should be only 'a'?_ That's a setting. I changed the default so that it doesn't mangle them anymore.

**Comment by olback** [comment]
You also asked for the documentation. Here are the sources i use:
[clean-css](https://www.npmjs.com/package/clean-css)  
[uglify-es](https://www.npmjs.com/package/uglify-es)
