### ISSUE TITLE
Sourcemap Path

### ISSUE THREAD

**Issue by AndrewHani** [olback/es6-css-minify#13]
Dears,
Thank you for the quick response on the last issue, but here I have a second one regarding the source map.
The path written at the end of both documents (min.js and min.js.map) are relative to my hard desk so I have to change it each time I minify.

I suggest to generate only the file name as they are in the same folder, so it would be relative the local and the uploaded folder.

Thank you..

**Comment by AndrewHani** [comment]
No.
The problem is that the path at the end of the minified version is
# sourceMappingURL=d:\Git\CairoGuide\JS\CairoGuideMain.min.js.map
So it's really relative to my hard drive, when it goes to a live server obviously it doesn't work, and same problem with the map file.
________________________________
De : Edwin <notifications@github.com>
Envoyé : dimanche 22 avril 2018 14:24
À : olback/es6-css-minify
Cc : Andrew Hani; Author
Objet : Re: [olback/es6-css-minify] Sourcemap Path (#13)


So you want style.css.map instead of style.min.css.map and the same for js?

**Comment by olback** [comment]
Ah, I'll see what I can do about that.

**Comment by AndrewHani** [comment]
Thank you for the magnificent work.
:D
________________________________
De : Edwin <notifications@github.com>
Envoyé : dimanche 22 avril 2018 17:24
À : olback/es6-css-minify
Cc : Andrew Hani; Author
Objet : Re: [olback/es6-css-minify] Sourcemap Path (#13)


There will be a setting called es6-css-minify.urlJSmap where the default value is an empty string (""). The default sourceMappingURL will just be the filename of the minified file.

**Comment by olback** [comment]
Update live!
