### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Fullstack-WEB-Blockchain-Developer** [olback/es6-css-minify#131]
- Issue Type: `Bug`
- Extension Name: `es6-css-minify`
- Extension Version: `3.3.2`
- OS Version: `Windows_NT x64 10.0.18362`
- VS Code version: `1.58.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by olback** [comment]
No bug has been described, closing due to lack of information.
