### ISSUE TITLE
Automatic Save

### ISSUE THREAD

**Issue by rsepierre** [olback/es6-css-minify#14]
Add new parameter for
"es6-css-minify.minifyOnSave" : true, false, exists

For parameter : exists : 
detects if a filename.min.extension already exists and only then minifies.

**Comment by olback** [comment]
This will be added in the next release.

**Comment by olback** [comment]
Oh, and do you think this should be the default instead of "yes"?

**Comment by rsepierre** [comment]
Cool. That's good news !

I think default behaviour should be "false" :

(After installing : You can manually minify, but nothing automatic &
potentially destructive has been set up).
So yes I'm guessing my recommendation for defaults would favor in that
order : false>if.min.exists>always

I wouldn't care for me because I always configure my extensions after
installing (and in this case, it's the reason I installed it).

**Comment by olback** [comment]
Update released!
