### ISSUE TITLE
Sourmap path

### ISSUE THREAD

**Issue by AndrewHani** [olback/es6-css-minify#18]
Dear Edwin,
I tried to minify but I always get this
//# sourceMappingURL=d:\Andrew\Tests\es6-minfy\main.min.js

Only if I fill "es6-css-minify.jsMapUrl" then I get
//# sourceMappingURL=testd:\Andrew\Tests\es6-minfy\main.min.js

**Comment by olback** [comment]
Did you run `Minify: Reload config`?

**Comment by AndrewHani** [comment]
No,
How is it done?

**Comment by olback** [comment]
Click F1, type `Minify: Reload config`.

**Comment by AndrewHani** [comment]
I did, and I got this message
ES5/ES6/CSS Minifier config reloaded

But it's still the same path

**Comment by olback** [comment]
You have to re-minify the file. Also, what version of the extension are you using? I just pushed version 0.1.2. And this feature works for me.

**Comment by AndrewHani** [comment]
0.1.2
I deleted the files and reminified, but it's always the same thing

I'll tell you my steps
I installed the extension, changed the settings to sourcemap to true, ran the task and saved so it generated the files, but with relative path to my computer.

**Comment by olback** [comment]
I think I know what's going on here. You're using Windows, right? I split the path at "/" but Windows paths are with "\". Working on it.

**Comment by AndrewHani** [comment]
Yes, I'm on windows.

**Comment by olback** [comment]
I have a lesson now, can't push an update right now. Should be up in a few hours though.

**Comment by AndrewHani** [comment]
OK.
Thanks for your enormous  efforts.
Good luck.

**Comment by olback** [comment]
Published.

**Comment by AndrewHani** [comment]
Great.
One final thing
In the generated map it refers to minified version on top of the file instead of referring to the unminified.
________________________________
De : Edwin <notifications@github.com>
Envoyé : lundi 23 avril 2018 13:01
À : olback/es6-css-minify
Cc : Andrew Hani; Author
Objet : Re: [olback/es6-css-minify] Sourmap path (#18)


Published.

**Comment by olback** [comment]
Yeah but shouldn't the sourcemap file be called `name.js.map`.map instead of `main.min.js.map` as well then?

**Comment by AndrewHani** [comment]
There is no problem with the source map naming, it's just how it refers the original file
meaning that in the map file I find
{"version":3,"sources":["CairoGuideMain.min.js"],
so it call the minified version twice on the inspect tool on the browser.

When I changed it manually to
{"version":3,"sources":["CairoGuideMain.js"],
It workss fine as it calls the minified version on load and the unminified version on inspector.

________________________________
De : Edwin <notifications@github.com>
Envoyé : lundi 23 avril 2018 13:28
À : olback/es6-css-minify
Cc : Andrew Hani; Author
Objet : Re: [olback/es6-css-minify] Sourmap path (#18)


Yeah but shouldn't the sourcemap file be called name.js.map.map instead of main.min.js.map as well then?

**Comment by olback** [comment]
I'll do the same for CSS then. No point in debugging a minified CSS file either I guess.

**Comment by AndrewHani** [comment]
Yes
________________________________
De : Edwin <notifications@github.com>
Envoyé : lundi 23 avril 2018 13:50
À : olback/es6-css-minify
Cc : Andrew Hani; Author
Objet : Re: [olback/es6-css-minify] Sourmap path (#18)


I'll do the same for CSS then. No point in debugging a minified CSS file either I guess.
