### ISSUE TITLE
Remove comments

### ISSUE THREAD

**Issue by chrtz** [olback/es6-css-minify#2]
Is it possible to add a function to remove comments from js/css while compiling it to a minified version?

**Comment by olback** [comment]
Comments should be removed. I tested both JS and CSS and comments were removed from both for me at least. Would you mind sharing a code-snippet I can test it on?

**Comment by chrtz** [comment]
Actually it seemed to be my fault.
Somehow I was sure to still see comments in VSCode. But they were removed
in the uploaded files. So everything works as expected.


Cheers.

Am 22.02.2018 13:42 schrieb "Edwin" <notifications@github.com>:

Comments should be removed. I tested both JS and CSS and comments were
removed from both for me at least. Would you mind sharing a code-snippet I
can test it on?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/olback/es6-css-minify/issues/2#issuecomment-367668771>,
or mute the thread

**Comment by olback** [comment]
No problem!
