### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by AndrewHani** [olback/es6-css-minify#20]
Dear Edwin,
I wonder if you can add an option for top level compression, meaning if I write var test = function(){...},
its minified to var a = function(){...}, it changes variables names to save more space, it's already supported by uglify.

Also it would be appreciated if you can add a feature where I can minify multiple js files into on file, which is also supported by uglify.

Thanks and regards..

**Comment by olback** [comment]
Top level compression can be enabled by changing "mangle" to true under "es6-css-minify.js". And as for multiple files, I don't know if that's what this plugin is for, really. I think you should take a look at something like [webpack](https://webpack.js.org/).

**Comment by AndrewHani** [comment]
Ok, I will..
Thank you.. :)

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
