### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by AndrewHani** [olback/es6-css-minify#21]
Dear Edwin,
I'm starting to have this message each time I minify, I uninstalled the extension, reinstalled it and ran the task of relod config but it doesn't work..
Thanks..

**Comment by olback** [comment]
Does this happen with both JS and CSS?

**Comment by AndrewHani** [comment]
Yes

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by olback** [comment]
I can't reproduce the issue. Can you provide example files, os and VS Code version?
Also, make sure you're using v0.1.5 of the extension.

**Comment by AndrewHani** [comment]
Windows.
Latest vs code version.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by AndrewHani** [comment]
I just tried to minfy on in a new project, it works.
I think it would be a contradiction with another extension..
I’ll check the others.

Sorry for disturbance

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by olback** [comment]
It should still work, what's in your `.vscode/settings.json` file?

**Comment by AndrewHani** [comment]
{
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressResultsExplorerNotice": false,
        "suppressShowKeyBindingsNotice": true,
        "suppressUpdateNotice": false,
        "suppressWelcomeNotice": true
    },
    "git.confirmSync": false,
    "git.autofetch": true,
    "liveSassCompile.settings.formats": [
        {
            "format": "compressed",
            "extensionName": ".css",
            "savePath": "/css"
        }
    ],
    "liveServer.settings.donotShowInfoMsg": true,
    "git.enableSmartCommit": true,
    "team.showWelcomeMessage": false,
    "gitlens.keymap": "chorded",
    "git-autoconfig.configList": [
        {
            "user.email": "andrew.gorgui@linkdev.com",
            "user.name": "m10agod14"
        },
        {
            "user.email": "andro_hani@hotmail.com",
            "user.name": "m10agod14"
        }
    ],
    "es6-css-minify.genCSSmap": true,
    "es6-css-minify.genJSmap": true,
    "es6-css-minify.js": {
        "mangle": false,
        "compress": {
            "unused": false
        },
        "output": {
            "quote_style": 0
        }
   }
}

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by olback** [comment]
All looks good, no idea why it isn't working, sorry.

**Comment by eletitos** [comment]
Hi! I just have wrote un issue since I have the same problem. I have 1.23.1 version of VS code and 0.1.5 version of ES5/ES6 minifier, in a macbook with OS X Yosemite.
I use the extension just to minify javascript. It may work at the same time with Live Sass Compiler extension and Live Server extension (probably any incompatibility?).
