### ISSUE TITLE
The extension host crashes when I use ES5/ES6 minifier in VScode

### ISSUE THREAD

**Issue by eletitos** [olback/es6-css-minify#22]
I have some problems with the stability of ES5/ES6 css minifier extension in visual studio code. When I use the extension for minifying javascript files the extension host crashes all the time and I need to reboot it. It´s really anoying because it happens a lot. I don´t find a solution I´m afraid I will uninstall the extexion. :(
I´m using version 1.23.1 in Visual Studio Code.

**Comment by olback** [comment]
I don't have this problem but it seems like it's the same issue as in #21.
Can you post a list of all your extensions?

**Comment by olback** [comment]
Closing due to lack of information.
