### ISSUE TITLE
How to set a filename pattern for creating the minified file?

### ISSUE THREAD

**Issue by infernocloud** [olback/es6-css-minify#23]
I'm moving from Atom and my minify plugin there let me specify a filename pattern for the minified file. Instead of a *.min.js file in the same directory I need to send the file to a "dist" directory and with no ".min" extension. Is there a way to do that using this plugin? If so I don't see how from the docs.

**Comment by olback** [comment]
There is no such feature as of right now. Should be added within a few days.

**Comment by olback** [comment]
Update published. If it doesn't work as requested, reopen this issue.

**Comment by robertoarise** [comment]
it does not work for me :(

my settings.json:
