### ISSUE TITLE
Combine multiple CSS and JS files in minified ones

### ISSUE THREAD

**Issue by ki11ua** [olback/es6-css-minify#25]
Is there a way to combine/bundle in one file all js and all css files in custom order or I have to use directly the script and command line function of clean-css and uglify-es? Thank you

**Comment by olback** [comment]
No there is no such function and I don't intend on adding one. Have you looked at webpack?

Thanks for the suggestion though.

**Comment by ki11ua** [comment]
Yes, I use webpack. I ask only for simplicity of use reasons. Thank you for your answer.
