### ISSUE TITLE
command 'es6-css-minify.minify' not found

### ISSUE THREAD

**Issue by AndrewLawendy** [olback/es6-css-minify#27]
Dear Edwin,
I started recently to find this message 'command 'es6-css-minify.minify' not found' when minifying CSS.
Thanks for taking care of it.

**Comment by AndrewLawendy** [comment]
Sorry only happened because I only opened the file not the folder.

**Comment by olback** [comment]
It's still a bug - reopening.

**Comment by olback** [comment]
Should be fixed in 2.0.0

**Comment by AndrewLawendy** [comment]
Great thanks

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by olback** [comment]
Update published.
