### ISSUE TITLE
Can't minify CSS files

### ISSUE THREAD

**Issue by dhtzs** [olback/es6-css-minify#28]
Just updated to version 2.0.0 today and now I'm not able to minify CSS files! The CSS files are located in a folder called 'css' in my project's root folder. I have tried moving them out of the folder and it simply doesn't work! I have also tried minifying CSS files on another project and it doesn't work either! This started happening when I updated to version 2.0.0.

**Comment by olback** [comment]
Did you click the Minify button or did you expect a minify job on-save?

**Comment by dhtzs** [comment]
I've tried clicking the Minify button, doing it with a keyboard shortcut, and clicking on 'Minify document' option! All of them do nothing, even though every time I try to minify a CSS file using one of these methods, there's a message saying 'Minified file is x.xx% smaller'.

Minify on save is disabled. I haven't changed any configuration!

**Comment by olback** [comment]
What's es6-css-minify.cssMinPath set to?

**Comment by dhtzs** [comment]
It's the default one (same directory). I tried changing it to '/' but it did nothing.

Note that minifying JS works as expected, if that helps

**Comment by olback** [comment]
I'm not at home right now so I can't do anything at the moment. I'll take a look as soon as I can.

**Comment by dhtzs** [comment]
Thank you!

**Comment by olback** [comment]
Update pushed to marketplace.
Thanks for reporting!

**Comment by Dimitris1337** [comment]
It's now working! Thanks! :)
