### ISSUE TITLE
Unexpected Renaming of Minified File

### ISSUE THREAD

**Issue by lyndonjohn** [olback/es6-css-minify#35]
First, thank you for this extension.

I have a js file, <strong>user.script.js</strong>.
When I minified it, it was renamed to <strong>usersscript.min.js</strong>.
I was expecting the new filename would be <strong>users.script.min.js</strong>.

Other than that, the minified file works.

**Comment by lyndonjohn** [comment]
Thank you @olback.

**Comment by olback** [comment]
Version 2.0.3 should be available now.
Thanks for reporting this issue.
