### ISSUE TITLE
Minifying feature not working at all

### ISSUE THREAD

**Issue by Benoit1980** [olback/es6-css-minify#43]
Visual CODE STUDIO v1.27.2
Windows 10 Pro 64 Bit

When I go to my CSS file, click on "F1", then "Minify Document", I can see at the bottom left of the screen a message saying:
"Minified file is 25% smaller", but no minification is happening on the page.

Any idea why, please?

Thank you,

**Comment by olback** [comment]
Have you changed any settings in the config?

**Comment by Benoit1980** [comment]
Sorry I will close this issue as I have downloaded another package. Thanks again.
