### ISSUE TITLE
Error "Minify failed: Cannot read property 'length' of undefined." when JS parsing fails

### ISSUE THREAD

**Issue by yozlet** [olback/es6-css-minify#45]
The error `Minify failed: Cannot read property 'length' of undefined.` has been appearing for me regularly when I run the "Minify document" command. It took me a while to work out that it was because JS parsing had failed, and then took more time to work out where the parsing error was. Now, I run `uglifyjs` on the command line to see what's going on.

I'm using version 2.0.3 of the extension with VSCode 1.28.0 on MacOS 10.13.6. This error happens whether I'm using a `.uglifyrc` or not. I'm not doing any CSS minification, only JS.

**Expected behavior**

The error should explain that there's been a parsing failure, and reproduce the parse error from uglifyjs. Ideally, it should make it easy to jump to the point in the file where parsing fails.

**Comment by olback** [comment]
So this only happens when the JavaScript syntax is incorrect?

**Comment by yozlet** [comment]
I believe so, yes.

Since posting this issue, I noticed a few errors that were just `Minify failed`, without the additional `Cannot read...` part, though I've had a few more of those too.

**Comment by yozlet** [comment]
@olback Thanks for the quick fix!

**Comment by olback** [comment]
@yozlet No problem!
