### ISSUE TITLE
Auto shorten identify names

### ISSUE THREAD

**Issue by SoiTrang** [olback/es6-css-minify#49]
Please add "Auto shorten identify names" feature, include variables, constants and functions, thanks

**Comment by olback** [comment]
For what language? Javascript or CSS? For Javascript, there is a setting called `mangle` which truncates variables, functions, etc.

**Comment by SoiTrang** [comment]
Thanks for your response. I'm sorry for not to read the documentation carefully. I figure it out now. Everything works perfectly.

**Comment by olback** [comment]
You're welcome. Enjoy!
