### ISSUE TITLE
feature request: settings, minify on save

### ISSUE THREAD

**Issue by bax-** [olback/es6-css-minify#5]
I would love to add settings to this extensions.
I would be great to minify files on save and to be able to specify uglifyjs settings (e.g. mangle-properties etc.)

Thanks!

**Comment by olback** [comment]
This should now be implemented!

**Comment by bax-** [comment]
`es6-css-minify.minifyOnSave` only works for css-files for me, not for js files…

**Comment by bax-** [comment]
and yet another request (should I open another issue?):
It would be great if I could link the config to e.g. .uglifyrc in my project folder.
That way es6-css-minify and nom scripts could all use the same configs.
Thanks!

**Comment by olback** [comment]
@bax- Open another issue for this.

**Comment by olback** [comment]
Minify JS on save should be fixed now.

**Comment by olback** [comment]
@bax- Should be on the marketplace now.
