### ISSUE TITLE
Minify JSON

### ISSUE THREAD

**Issue by FranklinYu** [olback/es6-css-minify#54]
It would be awesome if I can minify JSON with this extension.

**Comment by olback** [comment]
Something like this already exists: [eriklynd.json-tools](https://marketplace.visualstudio.com/items?itemName=eriklynd.json-tools). 
Thanks for the suggestion though!

**Comment by FranklinYu** [comment]
That one is not open-sourced. [andyyaldoo.vscode-json](https://marketplace.visualstudio.com/items?itemName=andyyaldoo.vscode-json) works and is open-sourced, so maybe this is not priority. Nevertheless I think it makes sense for all minification to be in one extension. (I don’t need “beautify” because that comes with VS Code.)

Or maybe review Pull Request if any?

**Comment by olback** [comment]
@FranklinYu I'll implement it as soon as I get the time to.

**Comment by olback** [comment]
Added in release `2.5.0`.
