### ISSUE TITLE
regex not working

### ISSUE THREAD

**Issue by MuTsunTsai** [olback/es6-css-minify#57]
**Describe the bug**
I was trying to use the `mangle.properties.regex` setting in `.uglifyrc` file, but no matter what I do, I always get either an immediate error on reloading the config or get a syntax error on executing minify.

**To Reproduce**
1. Add `mangle.properties.regex` setting in `.uglifyrc` file. JSON does not accept RegExp literals, and assigning string value leads to execution error.

**Expected behavior**
Expecting the extension will convert the string pattern into RegExp object and pass it to terser, but upon inspecting the source code, it doesn't do that.

**Additional context**
I temporarily fix the bug by adding the following under line 30 of `extension.js`:
```
if(_config.js.mangle && _config.js.mangle.properties && _config.js.mangle.properties.regex)
    _config.js.mangle.properties.regex = RegExp(_config.js.mangle.properties.regex);
```
But this is not general enough. Hope to see a general fix of this bug.

**Comment by olback** [comment]
Released under version 2.7.0.
