### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Shubzz-02** [olback/es6-css-minify#66]
- Issue Type: `Performance`
- Extension Name: `es6-css-minify`
- Extension Version: `2.5.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`
[olback.es6-css-minify-unresponsive.cpuprofile.txt](https://github.com/olback/es6-css-minify/files/3077805/olback.es6-css-minify-unresponsive.cpuprofile.txt)

**Comment by olback** [comment]
Version `2.6.0` is pushed to the marketplace. *Should* be fixed now!
