### ISSUE TITLE
Settings file

### ISSUE THREAD

**Issue by ToHe86** [olback/es6-css-minify#67]
Hi,

sorry for this maybe newb question: Where can I adjust the settings? I want to specify the path where the minified .js and .css are saved but don't get it working.

Thank you

**Comment by olback** [comment]
1. Click the cog in the bottom left.
2. Click 'Settings' in the list that pops up.
3. Search for `es6-css-minify` or `JS & CSS Minifier` (both works).

Now you should see all available settings. 
In your case you'd want to change 'CSS Min Path' and 'JS Min Path'.

All settings beginning with `Es6-CSS-minify` is settings provided by this extension.

**Comment by ToHe86** [comment]
Very nice thank you :)
