### ISSUE TITLE
Mangle options

### ISSUE THREAD

**Issue by rambhosale** [olback/es6-css-minify#69]
A setting/s to pass the mangle options

**Comment by olback** [comment]
These are the default settings and can be changed in `settings.json`.
```json
"es6-css-minify.js": {
        "mangle": false,
        "compress": {
            "unused": false
        },
        "output": {
            "quote_style": 0
        }
}
```
If the property `es6-css-minify.js` doesn't exist, just copy and paste the snippet above.

**Comment by olback** [comment]
@Rambhosale Is this resolved by now?

**Comment by rambhosale** [comment]
Thank you @olback got it working just the way I wanted it.
