### ISSUE TITLE
feature request: allow using external file for uglify / clean-css options

### ISSUE THREAD

**Issue by bax-** [olback/es6-css-minify#7]
I would love to be able to link in my options to an external file (or make it a default / "if-exists" setting).

By using e.g. `.uglifyrc`, npm-scripts and es6-css-minify could read from the same options and could apply the same magnification in different stages of development.

**Comment by olback** [comment]
So the extension should check if .uglifyrc exists, and if it does, overwrite the uglify-es settings with the ones specified in that file. And if the file doesn't exist, use the default settings. Correct?
And you want the same thing for clean-css? There does not seem to be a official config file option for clean-css so I guess I'll call it `.cssrc`?

**Comment by olback** [comment]
Let this be a bug-free release, please!

**Comment by olback** [comment]
I really need unit tests to make sure I don't break stuff....
