### ISSUE TITLE
How to use CSS Fragment Preservation

### ISSUE THREAD

**Issue by CubeRanch** [olback/es6-css-minify#74]
Hi,

I've been trying to use a feature introduced in clean-css v4.2, and I can't get it to work. It's described as:

"preserves any CSS content between /* clean-css ignore:start */ and /* clean-css ignore:end */ comments;"

What version of clean-css is bundled in your extension? I see the package.json for extension v2.7.0 specifies "@types/clean-css": "^3.4.30", but I haven't figure out how to determine what version was bundled.

Thanks

**Comment by olback** [comment]
Hi

The version in the package.json is what's bundled. The \@types/clean-css package does not specify the clean-css version. Type packages are only for typescript integration. Version 4.1.11 is what's bundled at the moment. I'll bump the version when I get back from my vacation!

**Comment by CubeRanch** [comment]
Brilliant! Thanks for the quick response.

> Version 4.1.11 is what's bundled at the moment.

Got it. I see that version further down the package.json.

BTW, thanks for the "Minify selection" command. I was actually looking for that functionality but didn't see it explicitly mentioned by any of the minify extensions. It was a nice surprise to find it in yours.

Cheers

**Comment by olback** [comment]
Sorry for taking so long to get this rather simple feature added. Ended up rewriting the whole thing and ran into a few issues. clean-css is now version `4.2.1`. Should be live on the marketplace in a few minutes!
