### ISSUE TITLE
Map files are not mapping with correct path

### ISSUE THREAD

**Issue by EvlBlackmask** [olback/es6-css-minify#76]
When generating a min file with a auto gen. map file the min file does not point to the map file. 

Example: When I minify a file it makes a min file and a map file named as such:
fileName.min.js
fileName.min.js.map

In the min file the map file location turn into:
fileName,js.map

I first saw this when version 3.0 came out. 
any help would be great! 
Thanks.

**Comment by olback** [comment]
Working on it!

Seems like both JS and CSS is affected.

**Comment by olback** [comment]
`3.0.1` is published now!
If it still does not work, just reopen the issue.
