### ISSUE TITLE
0.0.6: "command 'es6-css-minify.minify' not found"

### ISSUE THREAD

**Issue by bax-** [olback/es6-css-minify#8]
I don't know how but since updating from 0.0.5 to 0.0.6 I can't use es6-css-minify any more.
There is no `minify` button on the bottom any more and when I try to initiate the minifier through commands I get:
`command 'es6-css-minify.minify' not found`

I already deactivated/activated und uninstalled/reinstalled.

I didn't change the settings between versions

**Comment by olback** [comment]
Welp, it works in when running in dev-mode. I'm not getting any errors either, it just won't activate.

**Comment by olback** [comment]
The problem was that the vscode dependency was only included as a dev dependency, no idea why it worked in earlier versions, but hey. Should be good now.
