### ISSUE TITLE
Notification of config reload when no config change

### ISSUE THREAD

**Issue by CubeRanch** [olback/es6-css-minify#83]
I'm getting the "Minify configuration reloaded." message popping up very frequently when I haven't changed any configuration. Seems to be coming from the onDidChangeConfiguration() event. I don't think I noticed this before v3.

**To Reproduce**
1. Change editor tabs
2. Message pops up.

**Expected behavior**
I would only expect to see that message after saving settings.json.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 1809

**Comment by olback** [comment]
`onDidChangeConfiguration` is only supposed to fire when settings.json, or any other vscode file in `.vscode` is changed. It might be one of your extensions that changes something when switching tabs?

I agree with you, the notification show up when it shouldn't. Wokring on it.

I'm sorry for the slow reply.

**Comment by CubeRanch** [comment]
You nailed it. It's an extension called ColorTabs.
https://marketplace.visualstudio.com/items?itemName=orepor.color-tabs-vscode-ext
It calls settings.update on every tab change. Seems to be integral to the way it works, so I don't suppose there's much you can do about it.

Cheers

**Comment by olback** [comment]
There was something I could do about it actually. I now check if the change is related to the extension, if not, I'm just ignoring the event.

**Comment by CubeRanch** [comment]
Hah! Great.
