### ISSUE TITLE
@import

### ISSUE THREAD

**Issue by 0arra0** [olback/es6-css-minify#84]
Hey!
This expansion is really great. Keep it up.
I have only one problem in CSS. When I try to include a .css file into another .css file with @import "file.css";, I get the following error: "Ignoring local @import of "file.css" as resource is missing", although it exists.
I tried it with "es6-css-minify.css": { "inline": ["all"] } but I still get the error.
Am I doing something wrong?

**Comment by olback** [comment]
Thanks for using it! The error is thrown by clean-css, not the extension itself.

The problem probably occurs because the extension only pass the file content. I think clean-css needs to open the file directly.

**Comment by Delaney** [comment]
Having the same issue. Is there any solution?

**Comment by olback** [comment]
*Should* be fixed now.
