### ISSUE TITLE
[Errors]:1 - Name expected

### ISSUE THREAD

**Issue by dmopdyke** [olback/es6-css-minify#99]
Great extension. Been using without any issues, until today.
Got this error when minifying a .js file:

[Errors]: 1  - Name expected

I can't find any reference to this error. Could you please explain what's going on?

**Comment by olback** [comment]
Can you provide a code snippet so that I can reproduce the issue?

**Comment by dmopdyke** [comment]
Issue resolved. I tried an online minifier, and when I ran that file, an
error showed up in my code. Fixed the error, and Minify worked fine.
Do I need to mark the issue as closed, or something like that? First time
using Git-Hub this way...

**Comment by olback** [comment]
Glad you figured it out!

To answer your question about Github:
Either the person who opened the issue or one of the authors have to close it.

**Comment by dmopdyke** [comment]
Got it. Thanks!
